### ISSUE TITLE
go-header skips files not modified in the current calendar year

### ISSUE THREAD

**Issue by andrewkroh** [denis-tingaikin/go-header#22] opened 2022-02-24 19:30 UTC
While integrating go-header into an existing repo I found it surprising that none of my header checks were failing. I was intentionally trying to make go-header find problems by using a template that does not match my headers in order to verify it works.

If the file does not have a modification time matching the current year then the file is skipped by the checks. If your template changes then go-header won't detect the drift for older files (a similar comment was mentioned 
https://github.com/denis-tingaikin/go-header/issues/5#issuecomment-702706021).

https://github.com/denis-tingaikin/go-header/blob/a882f51323789142b21bf350dfa2ef1fdf88972c/analyzer.go#L59-L61

It seems like this check should be removed. If your use case is to allow headers with previous copyright years then use a regex or `{{year-range}}` in the template. And if your use is to ensure that headers have contain the current year then use the `{{year}}` variable.

**Comment by Antonboom** [comment] 2023-03-12 22:56
1) 
I suppose this check should be enabled only if year-builtins values used. This could solve the problem with the tests in `golangci-lint` – https://github.com/golangci/golangci-lint/issues/3682

2)
Without this check how to handle case when you need to have in copyright the last year of file change?

3)
It seems there is a more complex case. Copyright should reflect copyright holder, authors and specific years of file (not the entire project) changes.

Examples (from the Net):
```
// Copyright © 2022 John Doe. All rights reserved.
```
```
// Copyright © 2022-2096 Acme Corporation. All rights reserved.
// Author: John Doe
```
```
// Copyright © 2022 John Doe
// Copyright © 2023-2028 Jane Doe
// Copyright © 2028, 2030, 2032-2040, 2050-2096 Acme Corporation. Contacts: <acme@example.com>
// License: http://opensource.org/licenses/MIT
```

Looks like strong integration of linter with `git blame` – [example](https://github.com/cehteh/git-analyze-copyright).

<br/>

Also as temporary workaround maybe to introduce new built-in values:
- **MODTIME-YEAR** – Like **YEAR**, but expects year of last file modification. 
- **MODTIME-YEAR-RANGE** – Like **YEAR-RANGE**, but expects year of last file modification.
?

<br/>

(cc) @denis-tingaikin

**Comment by smyrman** [comment] 2023-03-17 08:39
I think `{{YEAR-RANGE}}` /`{{YEAR}}` changing to use the semantics described for `MODTIME-YEAR` and `MODTIME-YEAR-RANGE` in @Antonboom's comment would be a good fix for this issue.

Checking that copyright notices reflects copyright holders via git blame is more complex and deserves a separate issue if relevant. In some cases, copyright holder might not be well described by the Git Author information. E.g. the copyright holder could be a company or group, not the individual doing the contribution.

**Comment by Antonboom** [comment] 2023-10-01 10:09
@denis-tingaikin, what do you think?
I want to resolve this issue to support reproducible tests in `golangci-lint`.

**Comment by denis-tingaikin** [comment] 2023-10-01 11:58
@Antonboom Does https://github.com/denis-tingaikin/go-header/pull/32 fix the problem?

**Comment by Antonboom** [comment] 2023-10-01 12:03
> Does https://github.com/denis-tingaikin/go-header/pull/32 fix the problem?

To be honest I don't remember 🙈 
I think no, it's just a bugfix that I found by a chance.

**Comment by denis-tingaikin** [comment] 2023-10-01 12:20
I think we might start with adding a field in the go-header configuration. Something like `only-new-files: true` to allow checking old files

By default, if the goheader is using it directly, we think  `only-new-files: true`

In golangci-lint we could by default use `only-new-issues`  https://github.com/golangci/golangci-lint-action/issues/16

Thoughts?

**Comment by denis-tingaikin** [comment] 2024-02-18 16:25
Hello @andrewkroh , @Antonboom ,


I've prepared a fix for the problem because it's currently affecting testing for golangci linter guys.

Please have a look at https://github.com/denis-tingaikin/go-header/pull/39 when you get a chance. 

Am going to merge it until next Sunday, so feel free to add any comments, though!

**Comment by Antonboom** [comment] 2024-02-19 06:18
@denis-tingaikin, hi

could you please review and merge https://github.com/denis-tingaikin/go-header/pull/32 before?

**Closed** 2024-02-25 14:09 UTC
